FROM hgrasland/root-tests:6.20.04-cxx17

RUN zypper modifyrepo --enable repo-debug                                      \
    && zypper install -y perf gdb glibc-debuginfo libgcc_s1-debuginfo          \
                         libstdc++6-debuginfo                                  \
    && zypper clean -a

RUN mkdir /mnt/acts
COPY acts-build-worker.sh /root

RUN echo "Base system image built, see build.sh for next steps"